name: nga_fetcher_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0
  http: ^1.6.0
  html: ^0.15.6
  charset: ^2.0.1
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
